CREATE TABLE USERS (
       USER_ID INT PRIMARY KEY NOT NULL,
       USER_NAME VARCHAR(20),
       USER_LASTNAME VARCHAR(20),
       USER_PASSWORD VARCHAR(20),
       USER_PSEUDONYM VARCHAR(20),
       USER_MAIL VARCHAR(100),
       USER_AGE INT(2)
);
