CREATE TABLE USERS (
       USER_ID INT PRIMARY KEY NOT NULL,
       USER_NAME VARCHAR(20),
       USER_LASTNAME VARCHAR(20),
       USER_PASSWORD VARCHAR(20),
       USER_PSEUDONYM VARCHAR(20),
       USER_MAIL VARCHAR(100),
       USER_AGE INT(2),
       USER_WIN INT(3),
);

CREATE TABLE GAME (
       GAME_ID INT SERIAL PRIMARY KEY
       GAME_WINNER VARCHAR(20),
       GAME_LOSER VARCHAR(20),
       GAME_TIME INT(4),
       GAME_BTOKEN INT(2),
       GAME_WTOKEN INT(2),
);

CREATE TABLE RANKING (
       RANK_ID int serial primary key,
       RANK_NAME VARCHAR (20),
       RANK_PLAYER INT(3),
);


